### PR TITLE
Added hello world code in AspectJ

### PR DESCRIPTION
**Pull request by Suryanshj45**
try to merge it

### CODE REVIEW

**Review by mezotv — CHANGES_REQUESTED** [review]
The java code is a bit messy and def not the easiest way to print "Hello World!" and we already have elixer

**Comment by Suryanshj45** [comment]
ok

**Comment by Suryanshj45** [comment]
Added jquery code for printing hello world

**Comment by Suryanshj45** [comment]
Added jquery code for printing hello world

**Comment by mezotv** [comment]
That code also doesn't match the format. Ima close this now

**Pull request closed without merging**
