### PR TITLE
Create vimscript.vimrc

### PR DESCRIPTION
**Pull request by second007**
your order of vimscript has arrived

### CODE REVIEW

**Review by mezotv — APPROVED** [review]
Cool but uhm how do i exit vim?

**Comment by second007** [comment]
> Cool but uhm how do i exit vim?

Press the Esc key then you should see the ––INSERT–– label vanish from the lower-left, To save your changes before you exit, type :w , and then Enter. This will save any changes made. Vim will respond by outputting the filename, to exit Vi/Vim, type :q and hit Enter.

**Comment by mezotv** [comment]
> > Cool but uhm how do i exit vim?
> 
> Press the Esc key then you should see the ––INSERT–– label vanish from the lower-left, To save your changes before you exit, type :w , and then Enter. This will save any changes made. Vim will respond by outputting the filename, to exit Vi/Vim, type :q and hit Enter.

Thanks now i can recover the 15 macbooks ive lost to vim.

**Comment by mezotv** [comment]
> > Cool but uhm how do i exit vim?
> 
> Press the Esc key then you should see the ––INSERT–– label vanish from the lower-left, To save your changes before you exit, type :w , and then Enter. This will save any changes made. Vim will respond by outputting the filename, to exit Vi/Vim, type :q and hit Enter.

Im gonna go sleep soon so hit me up with the most crazy hello world languages you got for me.

**Pull request merged**
