### PR TITLE
Create whitespace.ws

### PR DESCRIPTION
**Pull request by sourcefactory-at**

### CODE REVIEW

**Comment by mezotv** [comment]
> No description provided.

Is there any way to run/test this code @sourcefactory-at

**Comment by sourcefactory-at** [comment]
Sure but needs of course a whitespace interpreter. The easiest would be to install it with `pip install whitespace`.

Then it can be directly run:
```
$ whitespace scripts/whitespace.ws 
Hello World!
```

**Comment by mezotv** [comment]
> Sure but needs of course a whitespace interpreter. The easiest would be to install it with `pip install whitespace`.
> 
> Then it can be directly run:
> 
> ```
> $ whitespace scripts/whitespace.ws 
> Hello World!
> ```

Writing whitespace sounds like a horrible thing to do. But as its a language ig we need to add it.

**Review by mezotv — APPROVED** [review]

**Comment by sourcefactory-at** [comment]
I fully agree but from time to time it's quite fun. No problem for me if it's too exotic for this list.

**Comment by mezotv** [comment]
> I fully agree but from time to time it's quite fun. No problem for me if it's too exotic for this list.

This list will include every language one day so this needs to be part of it. Better getting the hard ones first then the easy ones.

**Pull request merged**
