### PR TITLE
Create hack

### PR DESCRIPTION
**Pull request by bhoomitri4**
Hello World! in Hack

### CODE REVIEW

**Review by mezotv — CHANGES_REQUESTED** [review]
Does hack have a file ending or is it just hack?

**Comment by bhoomitri4** [comment]
since it is a dialect of PHP,  probably it uses .php extension. in vscode hack language extension .php is used

**Comment by mezotv** [comment]
Yea since its so similar to php I don't think there is a reason to add hack! Sorry

**Comment by bhoomitri4** [comment]
OK. Thanks

**Pull request closed without merging**
